# Generated by Django 5.2.8 on 2025-12-24 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("date_end", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "NEW"),
                            ("in_progress", "IN_PROGRESS"),
                            ("completed", "COMPLETED"),
                        ],
                        default="new",
                        max_length=100,
                    ),
                ),
                (
                    "Executor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="DjangoApp.team"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("firstName", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "ADMIN"), ("user", "USER")],
                        default="user",
                        max_length=100,
                    ),
                ),
                (
                    "tasks",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DjangoApp.task",
                    ),
                ),
            ],
        ),
    ]
