# Generated by Django 5.2.8 on 2025-12-24 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DjangoApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="tasks",
        ),
        migrations.AddField(
            model_name="user",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="DjangoApp.team",
            ),
        ),
    ]
