# Generated by Django 5.2.8 on 2025-12-30 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("DjangoApp", "0003_person_alter_task_executor_delete_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="name",
            new_name="title",
        ),
    ]
