# Generated by Django 5.2.8 on 2026-01-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DjangoApp", "0004_rename_name_team_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "new"),
                    ("in_progress", "in_progress"),
                    ("completed", "completed"),
                ],
                default="new",
                max_length=100,
            ),
        ),
    ]
